// This file is auto-generated by @hey-api/openapi-ts

export const AccessibilityAddModelSchema = {
    properties: {
        accessibility_ids: {
            description: 'List of accessibility IDs',
            items: {
                type: 'integer'
            },
            title: 'Accessibility Ids',
            type: 'array'
        }
    },
    required: ['accessibility_ids'],
    title: 'AccessibilityAddModel',
    type: 'object'
} as const;

export const AccessibilityDataSchema = {
    properties: {
        id: {
            description: 'Accessibility ID',
            title: 'Id',
            type: 'integer'
        },
        type: {
            description: 'Accessibility type',
            title: 'Type',
            type: 'string'
        }
    },
    required: ['id', 'type'],
    title: 'AccessibilityData',
    type: 'object'
} as const;

export const AccessibilityListResponseSchema = {
    properties: {
        accessibilities: {
            description: 'List of accessibilities',
            items: {
                '$ref': '#/components/schemas/AccessibilityData'
            },
            title: 'Accessibilities',
            type: 'array'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['accessibilities'],
    title: 'AccessibilityListResponse',
    type: 'object'
} as const;

export const ErrorResponseSchema = {
    properties: {
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Detailed error information',
            title: 'Error'
        },
        message: {
            description: 'Error message',
            title: 'Message',
            type: 'string'
        },
        success: {
            default: false,
            description: 'Error status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['message'],
    title: 'ErrorResponse',
    type: 'object'
} as const;

export const LoginSuccessResponseSchema = {
    properties: {
        message: {
            description: 'Success message',
            title: 'Message',
            type: 'string'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        },
        user: {
            '$ref': '#/components/schemas/UserProfileData',
            description: 'User profile data'
        }
    },
    required: ['message', 'user'],
    title: 'LoginSuccessResponse',
    type: 'object'
} as const;

export const MatchedPropertiesResponseSchema = {
    properties: {
        matched_properties: {
            description: 'List of matched properties',
            items: {
                '$ref': '#/components/schemas/PropertyData'
            },
            title: 'Matched Properties',
            type: 'array'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['matched_properties'],
    title: 'MatchedPropertiesResponse',
    type: 'object'
} as const;

export const MatchedTenantsResponseSchema = {
    properties: {
        matched_tenants: {
            description: 'List of matched tenants',
            items: {
                '$ref': '#/components/schemas/TenantData'
            },
            title: 'Matched Tenants',
            type: 'array'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['matched_tenants'],
    title: 'MatchedTenantsResponse',
    type: 'object'
} as const;

export const PreferencesFormDataSchema = {
    properties: {
        bathrooms: {
            description: 'Number of bathrooms',
            title: 'Bathrooms',
            type: 'string'
        },
        bedrooms: {
            description: 'Number of bedrooms',
            title: 'Bedrooms',
            type: 'string'
        },
        price: {
            description: 'Price',
            title: 'Price',
            type: 'string'
        },
        size_sqft: {
            description: 'Size in square feet',
            title: 'Size Sqft',
            type: 'string'
        }
    },
    required: ['size_sqft', 'price', 'bedrooms', 'bathrooms'],
    title: 'PreferencesFormData',
    type: 'object'
} as const;

export const ProfileResponseSchema = {
    properties: {
        profile: {
            additionalProperties: true,
            description: 'User profile data',
            title: 'Profile',
            type: 'object'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['profile'],
    title: 'ProfileResponse',
    type: 'object'
} as const;

export const PropertyCreateFormDataSchema = {
    properties: {
        bathrooms: {
            description: 'Number of bathrooms',
            title: 'Bathrooms',
            type: 'string'
        },
        bedrooms: {
            description: 'Number of bedrooms',
            title: 'Bedrooms',
            type: 'string'
        },
        city: {
            description: 'City',
            title: 'City',
            type: 'string'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: '',
            description: 'Property description',
            title: 'Description'
        },
        name: {
            description: 'Property name',
            title: 'Name',
            type: 'string'
        },
        price: {
            description: 'Price',
            title: 'Price',
            type: 'string'
        },
        size_sqft: {
            description: 'Size in square feet',
            title: 'Size Sqft',
            type: 'string'
        },
        street_address: {
            description: 'Street address',
            title: 'Street Address',
            type: 'string'
        }
    },
    required: ['size_sqft', 'price', 'bedrooms', 'bathrooms', 'street_address', 'city', 'name'],
    title: 'PropertyCreateFormData',
    type: 'object'
} as const;

export const PropertyCreateSuccessResponseSchema = {
    properties: {
        message: {
            description: 'Success message',
            title: 'Message',
            type: 'string'
        },
        property_id: {
            description: 'ID of the created property',
            title: 'Property Id',
            type: 'integer'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['message', 'property_id'],
    title: 'PropertyCreateSuccessResponse',
    type: 'object'
} as const;

export const PropertyDataSchema = {
    properties: {
        accessibilities: {
            default: [],
            description: 'List of accessibility types',
            items: {
                type: 'string'
            },
            title: 'Accessibilities',
            type: 'array'
        },
        bathrooms: {
            description: 'Number of bathrooms',
            title: 'Bathrooms',
            type: 'integer'
        },
        bedrooms: {
            description: 'Number of bedrooms',
            title: 'Bedrooms',
            type: 'integer'
        },
        businessName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Business name',
            title: 'Businessname'
        },
        city: {
            description: 'City',
            title: 'City',
            type: 'string'
        },
        id: {
            description: 'Property ID',
            title: 'Id',
            type: 'integer'
        },
        image_url: {
            description: 'Image URL',
            title: 'Image Url',
            type: 'string'
        },
        name: {
            description: 'Property name',
            title: 'Name',
            type: 'string'
        },
        price: {
            description: 'Price',
            title: 'Price',
            type: 'number'
        },
        size_sqft: {
            description: 'Size in square feet',
            title: 'Size Sqft',
            type: 'number'
        },
        street: {
            description: 'Street address',
            title: 'Street',
            type: 'string'
        }
    },
    required: ['id', 'name', 'size_sqft', 'price', 'bedrooms', 'bathrooms', 'street', 'city', 'image_url'],
    title: 'PropertyData',
    type: 'object'
} as const;

export const PropertyDetailDataSchema = {
    properties: {
        accessibilities: {
            description: 'List of accessibility types',
            items: {
                type: 'string'
            },
            title: 'Accessibilities',
            type: 'array'
        },
        bathrooms: {
            description: 'Number of bathrooms',
            title: 'Bathrooms',
            type: 'integer'
        },
        bedrooms: {
            description: 'Number of bedrooms',
            title: 'Bedrooms',
            type: 'integer'
        },
        businessName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Business name',
            title: 'Businessname'
        },
        city: {
            description: 'City',
            title: 'City',
            type: 'string'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Property description',
            title: 'Description'
        },
        id: {
            description: 'Property ID',
            title: 'Id',
            type: 'integer'
        },
        image_url: {
            description: 'Primary image URL',
            title: 'Image Url',
            type: 'string'
        },
        images: {
            description: 'List of all image URLs',
            items: {
                type: 'string'
            },
            title: 'Images',
            type: 'array'
        },
        name: {
            description: 'Property name',
            title: 'Name',
            type: 'string'
        },
        price: {
            description: 'Price',
            title: 'Price',
            type: 'number'
        },
        size_sqft: {
            description: 'Size in square feet',
            title: 'Size Sqft',
            type: 'number'
        },
        street_address: {
            description: 'Street address',
            title: 'Street Address',
            type: 'string'
        },
        user_id: {
            description: 'User ID of the owner',
            title: 'User Id',
            type: 'integer'
        }
    },
    required: ['id', 'name', 'size_sqft', 'price', 'bedrooms', 'bathrooms', 'street_address', 'city', 'user_id', 'image_url', 'images', 'accessibilities'],
    title: 'PropertyDetailData',
    type: 'object'
} as const;

export const PropertyDetailResponseSchema = {
    properties: {
        property: {
            '$ref': '#/components/schemas/PropertyDetailData',
            description: 'Property details'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['property'],
    title: 'PropertyDetailResponse',
    type: 'object'
} as const;

export const PropertyEditFormDataSchema = {
    properties: {
        bathrooms: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of bathrooms',
            title: 'Bathrooms'
        },
        bedrooms: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of bedrooms',
            title: 'Bedrooms'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'City',
            title: 'City'
        },
        delete_image_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'IDs of images to delete',
            title: 'Delete Image Ids'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Property description',
            title: 'Description'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Property name',
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Price',
            title: 'Price'
        },
        size_sqft: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Size in square feet',
            title: 'Size Sqft'
        },
        street_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Street address',
            title: 'Street Address'
        }
    },
    title: 'PropertyEditFormData',
    type: 'object'
} as const;

export const PropertyListResponseSchema = {
    properties: {
        properties: {
            description: 'List of properties',
            items: {
                '$ref': '#/components/schemas/PropertyDetailData'
            },
            title: 'Properties',
            type: 'array'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['properties'],
    title: 'PropertyListResponse',
    type: 'object'
} as const;

export const PropertyMatchModelSchema = {
    properties: {
        property_id: {
            description: 'ID of the property to match',
            title: 'Property Id',
            type: 'integer'
        }
    },
    required: ['property_id'],
    title: 'PropertyMatchModel',
    type: 'object'
} as const;

export const SuccessResponseSchema = {
    properties: {
        message: {
            description: 'Success message',
            title: 'Message',
            type: 'string'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['message'],
    title: 'SuccessResponse',
    type: 'object'
} as const;

export const TenantDataSchema = {
    properties: {
        id: {
            description: 'Tenant ID',
            title: 'Id',
            type: 'integer'
        },
        propertyId: {
            description: 'Property ID',
            title: 'Propertyid',
            type: 'integer'
        },
        propertyName: {
            description: 'Property name',
            title: 'Propertyname',
            type: 'string'
        },
        tenantFirstName: {
            description: 'Tenant first name',
            title: 'Tenantfirstname',
            type: 'string'
        },
        tenantLastName: {
            description: 'Tenant last name',
            title: 'Tenantlastname',
            type: 'string'
        },
        tenantProfileImageUrl: {
            description: 'Tenant profile image URL',
            title: 'Tenantprofileimageurl',
            type: 'string'
        }
    },
    required: ['id', 'tenantFirstName', 'tenantLastName', 'tenantProfileImageUrl', 'propertyName', 'propertyId'],
    title: 'TenantData',
    type: 'object'
} as const;

export const UserDataSchema = {
    properties: {
        firstname: {
            description: 'First name',
            title: 'Firstname',
            type: 'string'
        },
        id: {
            description: 'User ID',
            title: 'Id',
            type: 'integer'
        },
        lastname: {
            description: 'Last name',
            title: 'Lastname',
            type: 'string'
        }
    },
    required: ['id', 'firstname', 'lastname'],
    title: 'UserData',
    type: 'object'
} as const;

export const UserListResponseSchema = {
    properties: {
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        },
        users: {
            description: 'List of users',
            items: {
                '$ref': '#/components/schemas/UserData'
            },
            title: 'Users',
            type: 'array'
        }
    },
    required: ['users'],
    title: 'UserListResponse',
    type: 'object'
} as const;

export const UserLoginModelSchema = {
    properties: {
        password: {
            description: 'Password',
            title: 'Password',
            type: 'string'
        },
        username: {
            description: 'Username',
            title: 'Username',
            type: 'string'
        }
    },
    required: ['username', 'password'],
    title: 'UserLoginModel',
    type: 'object'
} as const;

export const UserProfileDataSchema = {
    properties: {
        email: {
            description: 'Email address',
            title: 'Email',
            type: 'string'
        },
        id: {
            description: 'User ID',
            title: 'Id',
            type: 'integer'
        },
        role: {
            description: 'User role',
            title: 'Role',
            type: 'string'
        },
        username: {
            description: 'Username',
            title: 'Username',
            type: 'string'
        }
    },
    required: ['id', 'username', 'email', 'role'],
    title: 'UserProfileData',
    type: 'object'
} as const;

export const UserProfileResponseSchema = {
    properties: {
        profile: {
            additionalProperties: true,
            description: 'User profile data',
            title: 'Profile',
            type: 'object'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        }
    },
    required: ['profile'],
    title: 'UserProfileResponse',
    type: 'object'
} as const;

export const UserProfileUpdateFormDataSchema = {
    properties: {
        businessName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Business name (for landlords)',
            title: 'Businessname'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Email address',
            title: 'Email'
        },
        firstname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'First name',
            title: 'Firstname'
        },
        lastname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Last name',
            title: 'Lastname'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Phone number',
            title: 'Phone'
        }
    },
    title: 'UserProfileUpdateFormData',
    type: 'object'
} as const;

export const UserRegisterModelSchema = {
    properties: {
        businessName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Business name (required for landlords)',
            title: 'Businessname'
        },
        email: {
            description: 'Email address',
            title: 'Email',
            type: 'string'
        },
        firstName: {
            description: 'First name',
            title: 'Firstname',
            type: 'string'
        },
        lastName: {
            description: 'Last name',
            title: 'Lastname',
            type: 'string'
        },
        password: {
            description: 'Password',
            title: 'Password',
            type: 'string'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Phone number',
            title: 'Phone'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            description: 'User role (tenant or landlord)'
        },
        username: {
            description: 'Username',
            title: 'Username',
            type: 'string'
        }
    },
    required: ['username', 'email', 'password', 'firstName', 'lastName', 'role'],
    title: 'UserRegisterModel',
    type: 'object'
} as const;

export const UserRoleSchema = {
    enum: ['tenant', 'landlord'],
    title: 'UserRole',
    type: 'string'
} as const;

export const ValidationErrorModelSchema = {
    properties: {
        ctx: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'an optional object which contains values required to render the error message.',
            title: 'Error context'
        },
        loc: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: "the error's location as a list. ",
            title: 'Location'
        },
        msg: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'a computer-readable identifier of the error type.',
            title: 'Message'
        },
        type_: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'a human readable explanation of the error.',
            title: 'Error Type'
        }
    },
    title: 'ValidationErrorModel',
    type: 'object'
} as const;

export const VoucherCreateModelSchema = {
    properties: {
        expiration_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Expiration date of the voucher',
            title: 'Expiration Date'
        },
        family_members: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of family members',
            title: 'Family Members'
        },
        housing_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Type of housing',
            title: 'Housing Type'
        },
        price_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Price limit for the voucher',
            title: 'Price Limit'
        }
    },
    title: 'VoucherCreateModel',
    type: 'object'
} as const;

export const VoucherCreateSuccessResponseSchema = {
    properties: {
        message: {
            description: 'Success message',
            title: 'Message',
            type: 'string'
        },
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        },
        voucher_id: {
            description: 'ID of the created voucher',
            title: 'Voucher Id',
            type: 'integer'
        }
    },
    required: ['message', 'voucher_id'],
    title: 'VoucherCreateSuccessResponse',
    type: 'object'
} as const;

export const VoucherDataSchema = {
    properties: {
        expiration_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Expiration date of the voucher',
            title: 'Expiration Date'
        },
        family_members: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of family members',
            title: 'Family Members'
        },
        housing_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Type of housing',
            title: 'Housing Type'
        },
        id: {
            description: 'Voucher ID',
            title: 'Id',
            type: 'integer'
        },
        price_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Price limit for the voucher',
            title: 'Price Limit'
        }
    },
    required: ['id'],
    title: 'VoucherData',
    type: 'object'
} as const;

export const VoucherListResponseSchema = {
    properties: {
        success: {
            default: true,
            description: 'Success status',
            title: 'Success',
            type: 'boolean'
        },
        vouchers: {
            description: 'List of vouchers',
            items: {
                '$ref': '#/components/schemas/VoucherData'
            },
            title: 'Vouchers',
            type: 'array'
        }
    },
    required: ['vouchers'],
    title: 'VoucherListResponse',
    type: 'object'
} as const;

export const VoucherUpdateModelSchema = {
    properties: {
        expiration_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Expiration date of the voucher',
            title: 'Expiration Date'
        },
        family_members: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of family members',
            title: 'Family Members'
        },
        housing_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Type of housing',
            title: 'Housing Type'
        },
        price_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Price limit for the voucher',
            title: 'Price Limit'
        }
    },
    title: 'VoucherUpdateModel',
    type: 'object'
} as const;