// This file is auto-generated by @hey-api/openapi-ts

export type AccessibilityAddModel = {
    /**
     * List of accessibility IDs
     */
    accessibility_ids: Array<number>;
};

export type AccessibilityData = {
    /**
     * Accessibility ID
     */
    id: number;
    /**
     * Accessibility type
     */
    type: string;
};

export type AccessibilityListResponse = {
    /**
     * List of accessibilities
     */
    accessibilities: Array<AccessibilityData>;
    /**
     * Success status
     */
    success?: boolean;
};

export type ErrorResponse = {
    /**
     * Detailed error information
     */
    error?: string | null;
    /**
     * Error message
     */
    message: string;
    /**
     * Error status
     */
    success?: boolean;
};

export type LoginSuccessResponse = {
    /**
     * Success message
     */
    message: string;
    /**
     * Success status
     */
    success?: boolean;
    /**
     * User profile data
     */
    user: UserProfileData;
};

export type MatchedPropertiesResponse = {
    /**
     * List of matched properties
     */
    matched_properties: Array<PropertyData>;
    /**
     * Success status
     */
    success?: boolean;
};

export type MatchedTenantsResponse = {
    /**
     * List of matched tenants
     */
    matched_tenants: Array<TenantData>;
    /**
     * Success status
     */
    success?: boolean;
};

export type PreferencesFormData = {
    /**
     * Number of bathrooms
     */
    bathrooms: string;
    /**
     * Number of bedrooms
     */
    bedrooms: string;
    /**
     * Price
     */
    price: string;
    /**
     * Size in square feet
     */
    size_sqft: string;
};

export type ProfileResponse = {
    /**
     * User profile data
     */
    profile: {
        [key: string]: unknown;
    };
    /**
     * Success status
     */
    success?: boolean;
};

export type PropertyCreateFormData = {
    /**
     * Number of bathrooms
     */
    bathrooms: string;
    /**
     * Number of bedrooms
     */
    bedrooms: string;
    /**
     * City
     */
    city: string;
    /**
     * Property description
     */
    description?: string | null;
    /**
     * Property name
     */
    name: string;
    /**
     * Price
     */
    price: string;
    /**
     * Size in square feet
     */
    size_sqft: string;
    /**
     * Street address
     */
    street_address: string;
};

export type PropertyCreateSuccessResponse = {
    /**
     * Success message
     */
    message: string;
    /**
     * ID of the created property
     */
    property_id: number;
    /**
     * Success status
     */
    success?: boolean;
};

export type PropertyData = {
    /**
     * List of accessibility types
     */
    accessibilities?: Array<string>;
    /**
     * Number of bathrooms
     */
    bathrooms: number;
    /**
     * Number of bedrooms
     */
    bedrooms: number;
    /**
     * Business name
     */
    businessName?: string | null;
    /**
     * City
     */
    city: string;
    /**
     * Property ID
     */
    id: number;
    /**
     * Image URL
     */
    image_url: string;
    /**
     * Property name
     */
    name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Size in square feet
     */
    size_sqft: number;
    /**
     * Street address
     */
    street: string;
};

export type PropertyDetailData = {
    /**
     * List of accessibility types
     */
    accessibilities: Array<string>;
    /**
     * Number of bathrooms
     */
    bathrooms: number;
    /**
     * Number of bedrooms
     */
    bedrooms: number;
    /**
     * Business name
     */
    businessName?: string | null;
    /**
     * City
     */
    city: string;
    /**
     * Property description
     */
    description?: string | null;
    /**
     * Property ID
     */
    id: number;
    /**
     * Primary image URL
     */
    image_url: string;
    /**
     * List of all image URLs
     */
    images: Array<string>;
    /**
     * Property name
     */
    name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Size in square feet
     */
    size_sqft: number;
    /**
     * Street address
     */
    street_address: string;
    /**
     * User ID of the owner
     */
    user_id: number;
};

export type PropertyDetailResponse = {
    /**
     * Property details
     */
    property: PropertyDetailData;
    /**
     * Success status
     */
    success?: boolean;
};

export type PropertyEditFormData = {
    /**
     * Number of bathrooms
     */
    bathrooms?: string | null;
    /**
     * Number of bedrooms
     */
    bedrooms?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * IDs of images to delete
     */
    delete_image_ids?: Array<string> | null;
    /**
     * Property description
     */
    description?: string | null;
    /**
     * Property name
     */
    name?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Size in square feet
     */
    size_sqft?: string | null;
    /**
     * Street address
     */
    street_address?: string | null;
};

export type PropertyListResponse = {
    /**
     * List of properties
     */
    properties: Array<PropertyDetailData>;
    /**
     * Success status
     */
    success?: boolean;
};

export type PropertyMatchModel = {
    /**
     * ID of the property to match
     */
    property_id: number;
};

export type SuccessResponse = {
    /**
     * Success message
     */
    message: string;
    /**
     * Success status
     */
    success?: boolean;
};

export type TenantData = {
    /**
     * Tenant ID
     */
    id: number;
    /**
     * Property ID
     */
    propertyId: number;
    /**
     * Property name
     */
    propertyName: string;
    /**
     * Tenant first name
     */
    tenantFirstName: string;
    /**
     * Tenant last name
     */
    tenantLastName: string;
    /**
     * Tenant profile image URL
     */
    tenantProfileImageUrl: string;
};

export type UserData = {
    /**
     * First name
     */
    firstname: string;
    /**
     * User ID
     */
    id: number;
    /**
     * Last name
     */
    lastname: string;
};

export type UserListResponse = {
    /**
     * Success status
     */
    success?: boolean;
    /**
     * List of users
     */
    users: Array<UserData>;
};

export type UserLoginModel = {
    /**
     * Password
     */
    password: string;
    /**
     * Username
     */
    username: string;
};

export type UserProfileData = {
    /**
     * Email address
     */
    email: string;
    /**
     * User ID
     */
    id: number;
    /**
     * User role
     */
    role: string;
    /**
     * Username
     */
    username: string;
};

export type UserProfileResponse = {
    /**
     * User profile data
     */
    profile: {
        [key: string]: unknown;
    };
    /**
     * Success status
     */
    success?: boolean;
};

export type UserProfileUpdateFormData = {
    /**
     * Business name (for landlords)
     */
    businessName?: string | null;
    /**
     * Email address
     */
    email?: string | null;
    /**
     * First name
     */
    firstname?: string | null;
    /**
     * Last name
     */
    lastname?: string | null;
    /**
     * Phone number
     */
    phone?: string | null;
};

export type UserRegisterModel = {
    /**
     * Business name (required for landlords)
     */
    businessName?: string | null;
    /**
     * Email address
     */
    email: string;
    /**
     * First name
     */
    firstName: string;
    /**
     * Last name
     */
    lastName: string;
    /**
     * Password
     */
    password: string;
    /**
     * Phone number
     */
    phone?: string | null;
    /**
     * User role (tenant or landlord)
     */
    role: UserRole;
    /**
     * Username
     */
    username: string;
};

export type UserRole = 'tenant' | 'landlord';

export const UserRole = {
    TENANT: 'tenant',
    LANDLORD: 'landlord'
} as const;

export type ValidationErrorModel = {
    /**
     * an optional object which contains values required to render the error message.
     */
    ctx?: {
        [key: string]: unknown;
    } | null;
    /**
     * the error's location as a list.
     */
    loc?: Array<string> | null;
    /**
     * a computer-readable identifier of the error type.
     */
    msg?: string | null;
    /**
     * a human readable explanation of the error.
     */
    type_?: string | null;
};

export type VoucherCreateModel = {
    /**
     * Expiration date of the voucher
     */
    expiration_date?: string | null;
    /**
     * Number of family members
     */
    family_members?: number | null;
    /**
     * Type of housing
     */
    housing_type?: string | null;
    /**
     * Price limit for the voucher
     */
    price_limit?: number | null;
};

export type VoucherCreateSuccessResponse = {
    /**
     * Success message
     */
    message: string;
    /**
     * Success status
     */
    success?: boolean;
    /**
     * ID of the created voucher
     */
    voucher_id: number;
};

export type VoucherData = {
    /**
     * Expiration date of the voucher
     */
    expiration_date?: string | null;
    /**
     * Number of family members
     */
    family_members?: number | null;
    /**
     * Type of housing
     */
    housing_type?: string | null;
    /**
     * Voucher ID
     */
    id: number;
    /**
     * Price limit for the voucher
     */
    price_limit?: number | null;
};

export type VoucherListResponse = {
    /**
     * Success status
     */
    success?: boolean;
    /**
     * List of vouchers
     */
    vouchers: Array<VoucherData>;
};

export type VoucherUpdateModel = {
    /**
     * Expiration date of the voucher
     */
    expiration_date?: string | null;
    /**
     * Number of family members
     */
    family_members?: number | null;
    /**
     * Type of housing
     */
    housing_type?: string | null;
    /**
     * Price limit for the voucher
     */
    price_limit?: number | null;
};

export type PropertiesApiAccessibilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accessibilities';
};

export type PropertiesApiAccessibilitiesGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesApiAccessibilitiesGetError = PropertiesApiAccessibilitiesGetErrors[keyof PropertiesApiAccessibilitiesGetErrors];

export type PropertiesApiAccessibilitiesGetResponses = {
    /**
     * OK
     */
    200: AccessibilityListResponse;
};

export type PropertiesApiAccessibilitiesGetResponse = PropertiesApiAccessibilitiesGetResponses[keyof PropertiesApiAccessibilitiesGetResponses];

export type UsersApiCurrentUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/current-user';
};

export type UsersApiCurrentUserGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersApiCurrentUserGetError = UsersApiCurrentUserGetErrors[keyof UsersApiCurrentUserGetErrors];

export type UsersApiCurrentUserGetResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type UsersApiCurrentUserGetResponse = UsersApiCurrentUserGetResponses[keyof UsersApiCurrentUserGetResponses];

export type MatchesApiLandlordMatchedTenantsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/landlord/matched-tenants';
};

export type MatchesApiLandlordMatchedTenantsGetErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MatchesApiLandlordMatchedTenantsGetError = MatchesApiLandlordMatchedTenantsGetErrors[keyof MatchesApiLandlordMatchedTenantsGetErrors];

export type MatchesApiLandlordMatchedTenantsGetResponses = {
    /**
     * OK
     */
    200: MatchedTenantsResponse;
};

export type MatchesApiLandlordMatchedTenantsGetResponse = MatchesApiLandlordMatchedTenantsGetResponses[keyof MatchesApiLandlordMatchedTenantsGetResponses];

export type MatchesApiMatchPostData = {
    body: PropertyMatchModel;
    path?: never;
    query?: never;
    url: '/api/match';
};

export type MatchesApiMatchPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MatchesApiMatchPostError = MatchesApiMatchPostErrors[keyof MatchesApiMatchPostErrors];

export type MatchesApiMatchPostResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type MatchesApiMatchPostResponse = MatchesApiMatchPostResponses[keyof MatchesApiMatchPostResponses];

export type PropertiesApiPropertiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/properties';
};

export type PropertiesApiPropertiesGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesApiPropertiesGetError = PropertiesApiPropertiesGetErrors[keyof PropertiesApiPropertiesGetErrors];

export type PropertiesApiPropertiesGetResponses = {
    /**
     * OK
     */
    200: PropertyListResponse;
};

export type PropertiesApiPropertiesGetResponse = PropertiesApiPropertiesGetResponses[keyof PropertiesApiPropertiesGetResponses];

export type PropertiesApiPropertiesIntPropertyIdGetData = {
    body?: never;
    path: {
        /**
         * Property ID
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}';
};

export type PropertiesApiPropertiesIntPropertyIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesApiPropertiesIntPropertyIdGetError = PropertiesApiPropertiesIntPropertyIdGetErrors[keyof PropertiesApiPropertiesIntPropertyIdGetErrors];

export type PropertiesApiPropertiesIntPropertyIdGetResponses = {
    /**
     * OK
     */
    200: PropertyDetailResponse;
};

export type PropertiesApiPropertiesIntPropertyIdGetResponse = PropertiesApiPropertiesIntPropertyIdGetResponses[keyof PropertiesApiPropertiesIntPropertyIdGetResponses];

export type AccessibilityApiUserAccessibilityPostData = {
    body: PreferencesFormData;
    path?: never;
    query?: never;
    url: '/api/user/accessibility';
};

export type AccessibilityApiUserAccessibilityPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type AccessibilityApiUserAccessibilityPostError = AccessibilityApiUserAccessibilityPostErrors[keyof AccessibilityApiUserAccessibilityPostErrors];

export type AccessibilityApiUserAccessibilityPostResponses = {
    /**
     * Created
     */
    201: SuccessResponse;
};

export type AccessibilityApiUserAccessibilityPostResponse = AccessibilityApiUserAccessibilityPostResponses[keyof AccessibilityApiUserAccessibilityPostResponses];

export type MatchesApiUserMatchedPropertiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/matched-properties';
};

export type MatchesApiUserMatchedPropertiesGetErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type MatchesApiUserMatchedPropertiesGetError = MatchesApiUserMatchedPropertiesGetErrors[keyof MatchesApiUserMatchedPropertiesGetErrors];

export type MatchesApiUserMatchedPropertiesGetResponses = {
    /**
     * OK
     */
    200: MatchedPropertiesResponse;
};

export type MatchesApiUserMatchedPropertiesGetResponse = MatchesApiUserMatchedPropertiesGetResponses[keyof MatchesApiUserMatchedPropertiesGetResponses];

export type UsersApiUserProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type UsersApiUserProfileGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersApiUserProfileGetError = UsersApiUserProfileGetErrors[keyof UsersApiUserProfileGetErrors];

export type UsersApiUserProfileGetResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type UsersApiUserProfileGetResponse = UsersApiUserProfileGetResponses[keyof UsersApiUserProfileGetResponses];

export type UsersApiUserUpdateProfilePutData = {
    body: UserProfileUpdateFormData;
    path?: never;
    query?: never;
    url: '/api/user/update-profile';
};

export type UsersApiUserUpdateProfilePutErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersApiUserUpdateProfilePutError = UsersApiUserUpdateProfilePutErrors[keyof UsersApiUserUpdateProfilePutErrors];

export type UsersApiUserUpdateProfilePutResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type UsersApiUserUpdateProfilePutResponse = UsersApiUserUpdateProfilePutResponses[keyof UsersApiUserUpdateProfilePutResponses];

export type UsersApiUserIntUserIdGetData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        user_id: number;
    };
    query?: never;
    url: '/api/user/{user_id}';
};

export type UsersApiUserIntUserIdGetErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersApiUserIntUserIdGetError = UsersApiUserIntUserIdGetErrors[keyof UsersApiUserIntUserIdGetErrors];

export type UsersApiUserIntUserIdGetResponses = {
    /**
     * OK
     */
    200: UserProfileResponse;
};

export type UsersApiUserIntUserIdGetResponse = UsersApiUserIntUserIdGetResponses[keyof UsersApiUserIntUserIdGetResponses];

export type UsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersApiUsersGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersApiUsersGetError = UsersApiUsersGetErrors[keyof UsersApiUsersGetErrors];

export type UsersApiUsersGetResponses = {
    /**
     * OK
     */
    200: UserListResponse;
};

export type UsersApiUsersGetResponse = UsersApiUsersGetResponses[keyof UsersApiUsersGetResponses];

export type VoucherApiVoucherCreatePostData = {
    body: VoucherCreateModel;
    path?: never;
    query?: never;
    url: '/api/voucher/create';
};

export type VoucherApiVoucherCreatePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VoucherApiVoucherCreatePostError = VoucherApiVoucherCreatePostErrors[keyof VoucherApiVoucherCreatePostErrors];

export type VoucherApiVoucherCreatePostResponses = {
    /**
     * Created
     */
    201: VoucherCreateSuccessResponse;
};

export type VoucherApiVoucherCreatePostResponse = VoucherApiVoucherCreatePostResponses[keyof VoucherApiVoucherCreatePostResponses];

export type VoucherApiVoucherDeleteIntVoucherIdDeleteData = {
    body?: never;
    path: {
        /**
         * ID of the voucher to delete
         */
        voucher_id: number;
    };
    query?: never;
    url: '/api/voucher/delete/{voucher_id}';
};

export type VoucherApiVoucherDeleteIntVoucherIdDeleteErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VoucherApiVoucherDeleteIntVoucherIdDeleteError = VoucherApiVoucherDeleteIntVoucherIdDeleteErrors[keyof VoucherApiVoucherDeleteIntVoucherIdDeleteErrors];

export type VoucherApiVoucherDeleteIntVoucherIdDeleteResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type VoucherApiVoucherDeleteIntVoucherIdDeleteResponse = VoucherApiVoucherDeleteIntVoucherIdDeleteResponses[keyof VoucherApiVoucherDeleteIntVoucherIdDeleteResponses];

export type VoucherApiVoucherUpdateIntVoucherIdPutData = {
    body: VoucherUpdateModel;
    path: {
        /**
         * ID of the voucher to update
         */
        voucher_id: number;
    };
    query?: never;
    url: '/api/voucher/update/{voucher_id}';
};

export type VoucherApiVoucherUpdateIntVoucherIdPutErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VoucherApiVoucherUpdateIntVoucherIdPutError = VoucherApiVoucherUpdateIntVoucherIdPutErrors[keyof VoucherApiVoucherUpdateIntVoucherIdPutErrors];

export type VoucherApiVoucherUpdateIntVoucherIdPutResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type VoucherApiVoucherUpdateIntVoucherIdPutResponse = VoucherApiVoucherUpdateIntVoucherIdPutResponses[keyof VoucherApiVoucherUpdateIntVoucherIdPutResponses];

export type VoucherApiVoucherUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/voucher/user';
};

export type VoucherApiVoucherUserGetErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type VoucherApiVoucherUserGetError = VoucherApiVoucherUserGetErrors[keyof VoucherApiVoucherUserGetErrors];

export type VoucherApiVoucherUserGetResponses = {
    /**
     * OK
     */
    200: VoucherListResponse;
};

export type VoucherApiVoucherUserGetResponse = VoucherApiVoucherUserGetResponses[keyof VoucherApiVoucherUserGetResponses];

export type AuthLoginPostData = {
    body: UserLoginModel;
    path?: never;
    query?: never;
    url: '/login';
};

export type AuthLoginPostErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type AuthLoginPostError = AuthLoginPostErrors[keyof AuthLoginPostErrors];

export type AuthLoginPostResponses = {
    /**
     * OK
     */
    200: LoginSuccessResponse;
};

export type AuthLoginPostResponse = AuthLoginPostResponses[keyof AuthLoginPostResponses];

export type AuthLogoutGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type AuthLogoutGetErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type AuthLogoutGetError = AuthLogoutGetErrors[keyof AuthLogoutGetErrors];

export type AuthLogoutGetResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type AuthLogoutGetResponse = AuthLogoutGetResponses[keyof AuthLogoutGetResponses];

export type PropertiesPropertyCreatePostData = {
    body: PropertyCreateFormData;
    path?: never;
    query?: never;
    url: '/property/create';
};

export type PropertiesPropertyCreatePostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesPropertyCreatePostError = PropertiesPropertyCreatePostErrors[keyof PropertiesPropertyCreatePostErrors];

export type PropertiesPropertyCreatePostResponses = {
    /**
     * Created
     */
    201: PropertyCreateSuccessResponse;
};

export type PropertiesPropertyCreatePostResponse = PropertiesPropertyCreatePostResponses[keyof PropertiesPropertyCreatePostResponses];

export type PropertiesPropertyDeleteIntPropertyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Property ID
         */
        property_id: number;
    };
    query?: never;
    url: '/property/delete/{property_id}';
};

export type PropertiesPropertyDeleteIntPropertyIdDeleteErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesPropertyDeleteIntPropertyIdDeleteError = PropertiesPropertyDeleteIntPropertyIdDeleteErrors[keyof PropertiesPropertyDeleteIntPropertyIdDeleteErrors];

export type PropertiesPropertyDeleteIntPropertyIdDeleteResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type PropertiesPropertyDeleteIntPropertyIdDeleteResponse = PropertiesPropertyDeleteIntPropertyIdDeleteResponses[keyof PropertiesPropertyDeleteIntPropertyIdDeleteResponses];

export type PropertiesPropertyEditIntPropertyIdPutData = {
    body: PropertyEditFormData;
    path: {
        /**
         * Property ID
         */
        property_id: number;
    };
    query?: never;
    url: '/property/edit/{property_id}';
};

export type PropertiesPropertyEditIntPropertyIdPutErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesPropertyEditIntPropertyIdPutError = PropertiesPropertyEditIntPropertyIdPutErrors[keyof PropertiesPropertyEditIntPropertyIdPutErrors];

export type PropertiesPropertyEditIntPropertyIdPutResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type PropertiesPropertyEditIntPropertyIdPutResponse = PropertiesPropertyEditIntPropertyIdPutResponses[keyof PropertiesPropertyEditIntPropertyIdPutResponses];

export type PropertiesPropertyIntPropertyIdAddAccessibilityPostData = {
    body: AccessibilityAddModel;
    path: {
        /**
         * Property ID
         */
        property_id: number;
    };
    query?: never;
    url: '/property/{property_id}/add-accessibility';
};

export type PropertiesPropertyIntPropertyIdAddAccessibilityPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PropertiesPropertyIntPropertyIdAddAccessibilityPostError = PropertiesPropertyIntPropertyIdAddAccessibilityPostErrors[keyof PropertiesPropertyIntPropertyIdAddAccessibilityPostErrors];

export type PropertiesPropertyIntPropertyIdAddAccessibilityPostResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type PropertiesPropertyIntPropertyIdAddAccessibilityPostResponse = PropertiesPropertyIntPropertyIdAddAccessibilityPostResponses[keyof PropertiesPropertyIntPropertyIdAddAccessibilityPostResponses];

export type UploadsPropertyPropertyIdUploadImagesPostData = {
    body?: never;
    path: {
        /**
         * ID of the property
         */
        property_id: number;
    };
    query?: never;
    url: '/property/{property_id}/upload-images';
};

export type UploadsPropertyPropertyIdUploadImagesPostErrors = {
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
};

export type UploadsPropertyPropertyIdUploadImagesPostError = UploadsPropertyPropertyIdUploadImagesPostErrors[keyof UploadsPropertyPropertyIdUploadImagesPostErrors];

export type AuthRegisterPostData = {
    body: UserRegisterModel;
    path?: never;
    query?: never;
    url: '/register';
};

export type AuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type AuthRegisterPostError = AuthRegisterPostErrors[keyof AuthRegisterPostErrors];

export type AuthRegisterPostResponses = {
    /**
     * Created
     */
    201: SuccessResponse;
};

export type AuthRegisterPostResponse = AuthRegisterPostResponses[keyof AuthRegisterPostResponses];

export type UploadsUploadsFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename of the uploaded file
         */
        filename: string;
    };
    query?: never;
    url: '/uploads/{filename}';
};

export type UploadsUploadsFilenameGetErrors = {
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
};

export type UploadsUploadsFilenameGetError = UploadsUploadsFilenameGetErrors[keyof UploadsUploadsFilenameGetErrors];

export type UsersUserDeleteIntUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        user_id: number;
    };
    query?: never;
    url: '/user/delete/{user_id}';
};

export type UsersUserDeleteIntUserIdDeleteErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Content
     */
    422: Array<ValidationErrorModel>;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type UsersUserDeleteIntUserIdDeleteError = UsersUserDeleteIntUserIdDeleteErrors[keyof UsersUserDeleteIntUserIdDeleteErrors];

export type UsersUserDeleteIntUserIdDeleteResponses = {
    /**
     * OK
     */
    200: SuccessResponse;
};

export type UsersUserDeleteIntUserIdDeleteResponse = UsersUserDeleteIntUserIdDeleteResponses[keyof UsersUserDeleteIntUserIdDeleteResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};